#!/usr/bin/env python3
"""
server.py - local web UI for the downloader.

Paste a URL, pick a destination folder, press Download. The job runs in the
background: fetch best audio -> split on chapters if the upload has them ->
convert to MP3 320 -> embed artwork. The destination folder is created if it
does not exist.

    python server.py
    python server.py --root "C:/Users/Public/AppleMusic" --port 8800
    python server.py --host 0.0.0.0 --token secret123      # exposing it

Security: binds to 127.0.0.1 by default and refuses to write outside --root.
If you put this behind a tunnel, set --token; without one, anyone who reaches
the page can download arbitrary URLs onto your machine.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import time
import uuid
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from pathlib import Path

HERE = Path(__file__).resolve().parent
JOBS = {}
JOBS_LOCK = threading.Lock()
CONFIG = {}


# ---------------------------------------------------------------- helpers

def find_exe(name):
    exe = shutil.which(name)
    if exe:
        return exe
    local = os.environ.get("LOCALAPPDATA")
    if local:
        hits = sorted(Path(local).glob(
            f"Microsoft/WinGet/Packages/Gyan.FFmpeg*/**/bin/{name}.exe"))
        if hits:
            return str(hits[-1])
    return None


def safe_target(folder):
    """Resolve a user-supplied folder, refusing anything outside --root.

    The folder box is free text, so without this a request could write to
    C:/Windows or anywhere else the process can reach.
    """
    root = Path(CONFIG["root"]).resolve()
    raw = (folder or "").strip().strip('"')
    if not raw:
        raise ValueError("No destination folder given")
    p = Path(raw)
    target = (root / p).resolve() if not p.is_absolute() else p.resolve()
    if root not in target.parents and target != root:
        raise ValueError(f"Destination must be inside {root}")
    return target


def log(job, line):
    line = line.rstrip()
    if not line:
        return
    with JOBS_LOCK:
        job["log"].append(line)
        del job["log"][:-400]          # keep the tail, not the whole history


def run(job, cmd, phase):
    """Run a subprocess, streaming its output into the job log."""
    with JOBS_LOCK:
        job["phase"] = phase
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                            text=True, bufsize=1, encoding="utf-8", errors="replace")
    for line in proc.stdout:
        log(job, line)
        m = re.search(r"(\d{1,3}(?:\.\d)?)%", line)
        if m:
            with JOBS_LOCK:
                job["percent"] = min(100, float(m.group(1)))
    proc.wait()
    return proc.returncode


def write_cue(path, chapters, meta):
    """Turn chapter markers into a cuesheet split_tracks.py can consume."""
    def stamp(sec):
        h, rem = divmod(float(sec), 3600)
        m, s = divmod(rem, 60)
        return f"{int(h)}:{int(m):02d}:{s:05.2f}" if h else f"{int(m)}:{s:05.2f}"

    lines = ["# generated by server.py from chapter markers", ""]
    for k in ("ALBUM", "ARTIST", "DATE"):
        lines.append(f"{k}: {meta.get(k, '')}")
    lines.append("")
    for i, c in enumerate(chapters):
        title = (c.get("title") or f"Track {i + 1:02d}").strip()
        lines.append(f"{stamp(c['start_time'])} - {stamp(c['end_time'])}    {title}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------- the job

def run_job(job):
    try:
        target = safe_target(job["folder"])
        target.mkdir(parents=True, exist_ok=True)
        with JOBS_LOCK:
            job["output"] = str(target)
        log(job, f"Destination: {target}")

        work = target / ".work"
        work.mkdir(exist_ok=True)

        # 1. download best audio, plus the metadata and thumbnail in one pass
        rc = run(job, [sys.executable, "-m", "yt_dlp",
                       "-f", "bestaudio/best",
                       "-o", str(work / "%(title)s.%(ext)s"),
                       "--write-info-json", "--write-thumbnail",
                       "--no-playlist" if not job["playlist"] else "--yes-playlist",
                       "--newline", job["url"]], "Downloading")
        if rc != 0:
            raise RuntimeError("Download failed - see log")

        info_files = sorted(work.glob("*.info.json"))
        if not info_files:
            raise RuntimeError("No metadata written; download may have failed")
        info = json.loads(info_files[0].read_text(encoding="utf-8", errors="replace"))

        audio = next((f for f in sorted(work.iterdir())
                      if f.suffix.lower() in {".m4a", ".webm", ".opus", ".mp3",
                                              ".ogg", ".flac", ".wav"}), None)
        if not audio:
            raise RuntimeError("Downloaded file not found")
        log(job, f"Got: {audio.name}")

        # Fall back to the uploader only when nothing better was given - a YouTube
        # channel name is rarely the artist you want in a library.
        title = info.get("title") or audio.stem
        album = job["album"] or info.get("album") or title
        artist = job["artist"] or info.get("artist") or info.get("uploader") or ""
        date = job["date"] or str(info.get("release_year") or "")
        chapters = info.get("chapters") or []

        # 2. chapters -> split into tracks; otherwise keep it as one file
        if chapters and job["split"]:
            log(job, f"{len(chapters)} chapters found - splitting")
            cue = work / "cue.txt"
            write_cue(cue, chapters, {"ALBUM": album, "ARTIST": artist, "DATE": date})
            rc = run(job, [sys.executable, str(HERE / "split_tracks.py"), str(audio),
                           "--cue", str(cue), "--format", job["format"],
                           "-q", str(job["bitrate"]), "-o", str(target)], "Splitting")
            if rc != 0:
                raise RuntimeError("Split failed - see log")
        else:
            if job["split"] and not chapters:
                log(job, "No chapters on this upload - keeping as a single track")
            ffmpeg = find_exe("ffmpeg")
            if not ffmpeg:
                raise RuntimeError("ffmpeg not found")
            dest = target / f"{re.sub(r'[<>:\"/\\\\|?*]', '_', title)}.{job['format']}"
            with JOBS_LOCK:
                job["phase"] = "Converting"
            cmd = [ffmpeg, "-hide_banner", "-loglevel", "error", "-y",
                   "-i", str(audio), "-map", "0:a"]
            if job["format"] != "flac":
                cmd += ["-b:a", f"{job['bitrate']}k"]
            cmd += ["-metadata", f"title={title}"]
            for tag, val in (("artist", artist), ("album", album), ("date", date)):
                if val:
                    cmd += ["-metadata", f"{tag}={val}"]
            cmd.append(str(dest))
            if subprocess.run(cmd, capture_output=True).returncode != 0:
                raise RuntimeError("Conversion failed")
            log(job, f"Wrote {dest.name}")

        # 3. artwork, from the thumbnail we already pulled down
        thumb = next((f for f in work.iterdir()
                      if f.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}), None)
        if thumb:
            rc = run(job, [sys.executable, str(HERE / "add_art.py"), str(thumb),
                           "-d", str(target)], "Artwork")
            if rc != 0:
                log(job, "Artwork step failed - tracks are still fine")
        else:
            log(job, "No thumbnail available; skipping artwork")

        shutil.rmtree(work, ignore_errors=True)
        made = sorted(f.name for f in target.iterdir() if f.is_file())
        with JOBS_LOCK:
            job.update(status="done", phase="Done", percent=100,
                       files=made, finished=time.time())
        log(job, f"Finished - {len([f for f in made if not f.endswith('.jpg')])} track(s)")

    except Exception as e:                                  # noqa: BLE001
        with JOBS_LOCK:
            job.update(status="error", phase="Failed", error=str(e),
                       finished=time.time())
        log(job, f"ERROR: {e}")


# ---------------------------------------------------------------- http

class Handler(BaseHTTPRequestHandler):
    server_version = "soundcloud-dl"

    def log_message(self, *a):
        pass                                                # quiet console

    def _send(self, code, body, ctype="application/json"):
        raw = body if isinstance(body, bytes) else str(body).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(raw)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(raw)

    def _authed(self):
        token = CONFIG.get("token")
        if not token:
            return True
        sent = (self.headers.get("X-Token") or "").strip()
        if sent == token:
            return True
        self._send(401, json.dumps({"error": "bad or missing token"}))
        return False

    def do_GET(self):
        path = self.path.split("?")[0]
        if path in ("/", "/index.html"):
            page = HERE / "web" / "index.html"
            if not page.exists():
                return self._send(500, "web/index.html is missing", "text/plain")
            return self._send(200, page.read_bytes(), "text/html; charset=utf-8")

        if path == "/api/config":
            return self._send(200, json.dumps({
                "root": CONFIG["root"],
                "needsToken": bool(CONFIG.get("token")),
                "formats": ["mp3", "m4a", "flac"],
            }))

        if path.startswith("/api/jobs"):
            if not self._authed():
                return
            jid = path.rsplit("/", 1)[-1]
            with JOBS_LOCK:
                if jid and jid != "jobs":
                    job = JOBS.get(jid)
                    if not job:
                        return self._send(404, json.dumps({"error": "no such job"}))
                    return self._send(200, json.dumps(job))
                recent = sorted(JOBS.values(), key=lambda j: -j["started"])[:20]
                return self._send(200, json.dumps([
                    {k: v for k, v in j.items() if k != "log"} for j in recent]))

        self._send(404, json.dumps({"error": "not found"}))

    def do_POST(self):
        if self.path.split("?")[0] != "/api/jobs":
            return self._send(404, json.dumps({"error": "not found"}))
        if not self._authed():
            return
        try:
            n = int(self.headers.get("Content-Length") or 0)
            body = json.loads(self.rfile.read(n) or b"{}")
        except (ValueError, json.JSONDecodeError):
            return self._send(400, json.dumps({"error": "bad JSON"}))

        url = (body.get("url") or "").strip()
        if not re.match(r"^https?://", url):
            return self._send(400, json.dumps({"error": "Enter a http(s) URL"}))
        try:
            safe_target(body.get("folder"))                 # validate before queueing
        except ValueError as e:
            return self._send(400, json.dumps({"error": str(e)}))

        job = {
            "id": uuid.uuid4().hex[:12],
            "url": url,
            "folder": (body.get("folder") or "").strip(),
            "artist": (body.get("artist") or "").strip(),
            "album": (body.get("album") or "").strip(),
            "date": (body.get("date") or "").strip(),
            "format": body.get("format") if body.get("format") in
                      ("mp3", "m4a", "flac") else "mp3",
            "bitrate": int(body.get("bitrate") or 320),
            "split": bool(body.get("split", True)),
            "playlist": bool(body.get("playlist", False)),
            "status": "running", "phase": "Starting", "percent": 0.0,
            "log": [], "files": [], "output": "", "error": "",
            "started": time.time(), "finished": 0,
        }
        with JOBS_LOCK:
            JOBS[job["id"]] = job
        threading.Thread(target=run_job, args=(job,), daemon=True).start()
        return self._send(200, json.dumps({"id": job["id"]}))


def main():
    p = argparse.ArgumentParser(description="Local web UI for the downloader.")
    p.add_argument("--host", default="127.0.0.1",
                   help="bind address (default: 127.0.0.1, local only)")
    p.add_argument("--port", type=int, default=8800)
    p.add_argument("--root", default=str(Path.home() / "Music"),
                   help="destination folders must live under this (default: ~/Music)")
    p.add_argument("--token", help="require this token in an X-Token header")
    args = p.parse_args()

    root = Path(args.root).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    CONFIG.update(root=str(root), token=args.token)

    if not find_exe("ffmpeg"):
        print("!! ffmpeg not found - conversion will fail.\n"
              "   winget install Gyan.FFmpeg\n")
    if args.host != "127.0.0.1" and not args.token:
        print("!! Bound to a public interface with no --token.\n"
              "   Anyone who can reach this page can download onto your machine.\n")

    print(f"  Root  : {root}")
    print(f"  Open  : http://{'localhost' if args.host == '127.0.0.1' else args.host}"
          f":{args.port}\n  Ctrl+C to stop.\n")
    try:
        ThreadingHTTPServer((args.host, args.port), Handler).serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
